version: '3'
services:
  app:
    container_name: first_app
    build: .
    ports: 
        - "8000:8000"
    volumes: 
        - ./project/node:/usr/src/app
    links: 
        - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
        - "27017:27017"