version: '3'
services:
  app:
    container_name: first_app
    build: .
    ports: 
        - "8000:8000"
    volumes: 
        - ./project/api/:/usr/src/app
    links: 
        - mongo
  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=testDB
    volumes: 
      - ./db-data:/data/db
    ports:
        - "27017:27017"